# Generated by Django 6.0.3 on 2026-04-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('records', '0002_rename_diagnosis_record_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='user_name',
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.record'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
