# Generated by Django 6.0.3 on 2026-04-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard'),
        ),
    ]
