# Generated by Django 6.0.3 on 2026-04-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_name_and_more'),
        ('records', '0002_rename_diagnosis_record_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=100),
        ),
    ]
