# Generated by Django 6.0.3 on 2026-04-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='diagnosis',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='record',
            name='recore_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_name',
        ),
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
